doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

        # If different apps use different migrations, you can uncomment this
        # and remove the one above.
        #'DoctrineMigrations': '%kernel.project_dir%/migrations/%kernel.name%'
    enable_profiler: false
