# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # This allows all the DataFixtures to be kept outside of the rest of the code
    # https://symfony.com/bundles/DoctrineFixturesBundle/current/index.html
    DataFixtures\:
        resource: '../fixtures'

    Shared\:
        resource: '../src/Shared'
        exclude:
            - '../src/Shared/Infrastructure/Doctrine/Entity/'
            - '../src/Shared/Infrastructure/Symfony/DependencyInjection/'
            - '../src/Shared/Infrastructure/Symfony/Entity/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
